### ISSUE TITLE
Should Extent be per-tile rather than per-layer ?

### ISSUE THREAD

**Issue by strk** [mapbox/vector-tile-spec#16]
The documentation for "extent" says  "The bounding box in this tile spans from 0..4095 units", but the "extent" is a parameter of a layer rather than a tile. Can different layers in a tile have different "extent" ?

**Comment by flippmoke** [comment]
I was was through old tickets as we were preparing to release a new version of the spec and wanted to make sure we addressed issues. This is because we attempt to make a layer a full set of information such that multiple layers can simply be concatenated together quickly to make a new dataset. The layers are intended to be independent. Therefore, we do not store anything globally.
