### ISSUE TITLE
Do every geometry need to be clipped ?

### ISSUE THREAD

**Issue by fnicollet** [mapbox/vector-tile-spec#26]
Hello,

This is more of a question than an issue. In the specs https://github.com/mapbox/vector-tile-spec/tree/master/1.0.1 it says that "Geometries are clipped, reprojected into spherical mercator, converted to screen coordinates".
Is it valid for every kind of geometry? If you look at the Java encoder implementation here:
https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L100
It clips only when not a polygon so linestring/multilinestring/points will be clipped (which is also weird because it then tests for a MultiPolygon type which is impossible if you clip a line, you will get a multilinestring in the worst case).
It just checks if polygons are within bounds of the tile but does not crop them.

In this message, @kkaefer says that Mapbox uses clipped geometry (with a small buffer around the tile, probably to account for line-style widths):
https://github.com/mapbox/vector-tile-spec/issues/6#issuecomment-42596780

This one says that the geometries can be clipped or not, the tile format is fine with either:
https://github.com/mapbox/vector-tile-spec/issues/8#issuecomment-42596518

I am producing my own tiles and getting rendering artefacts on some segments (lines and polygon weirdness) from mapbox-gl-js:
![image](https://cloud.githubusercontent.com/assets/1240481/5134048/a65f3b1c-710a-11e4-9604-50c21cb48a3e.png)

So I was wondering if clipping obligatory, at least reduce the tile size, and what MapBox does exactly when generating tiles when it comes to clipping

Thanks a lot for your help!
Fabien

**Comment by mariusnita** [comment]
@pramsey are you aware of work that uses "vector tiles as data" (as opposed to "vector tiles for better rendering" which is what mapbox seems to be doing), that is actually stitching the tiles on the frontend to recover the original vector data?

**Comment by fnicollet** [comment]
Hello,

This article might be interesting to you:
http://dimensionaledge.com/intro-vector-tiling-map-reduce-postgis/

Fabien

**Comment by mariusnita** [comment]
Thanks @fnicollet !

**Comment by ReynoldSong** [comment]
thanks @fnicollet @springmeyer @pramsey ! Your question and answer are very useful to me.

**Comment by xwhsky** [comment]
Thanks a lot. Really impressive!

**Comment by xwhsky** [comment]
@pramsey Another querstion, what's the application or research of vector tiles using its geometry and attributes on client without querying the remote web server.

**Comment by pramsey** [comment]
It's not impossible for vector tiles to be used as a source for client-side logic, but they'd either have to be clipped back to the real tile grid at the client before logic was applied, or provided by the server on the exact grid. In both cases, because they lacked a gutter they would not be useful for high-end rendering without further processing (polygons would need to be stitched back together, etc), though basic rendering would still work fine. 

The tile provider would need to adhere to some kind of contract around ensuring that features on different tiles shared a unique key, so they could be associated w/ one another after delivery. And finally, (and importantly) any analysis on client side would have to be careful of the fact that the MVT data has been quantized, so the coordinates are no longer exact. This could result in spurious results for things like touching tests, distance tests, etc, though all under the precision level of the quantization, which since it is a visually defined level might not bother you at all (your results would be consistent with what you could see on the screen).

Other simpler tiling schemes (I think of some of the stuff MapZen did early on in their tile experiments for example) qualify as more immediately usable, as they neither quantize the data (they just keep the coordinates in the global projection) nor bother to add a gutter to the tiles.

**Comment by xwhsky** [comment]
@pramsey really thanks, have so many harvest ! Generate some idea following your explain, hope you can guide:
1. quantized vector tile data is not precisely, should it be possible to be used in specific areas, such as duzzy query for filting and duzzy statistics?
2. attribute data exists in every zoom layer of one vector feature, are there some solutions of reducing redundant?
3. vector tiles cached in client are decided by user's map navigation, so what's the related applications of these custom vector tiles when they are used to be queried and analyzed?

**Comment by chriswhong** [comment]
On a project at work we are getting the best of both worlds using Carto's undocumented vector tiles + the SQL API.  We pass the SUMs and Counts and spatial joins to PostGIS to get values we can rely on, and only use the vector tiles for rendering.  We end up using the same workflow as updating raster tiles (Think `setSQL()`) which seems wasteful as a lot of redundant data comes over the wire, but it gets the job done.
