### ISSUE TITLE
LineTo(0,0) and Invalidation of POLYGON and LINESTRING geometries

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vector-tile-spec#51]
With [mapnik-vector-tile](https://github.com/mapbox/mapnik-vector-tile) implementation as I am upgrading to the stricter interpretation of V2, I have noticed an issue perhaps in our wording.

Within our decoder of geometries, I ignore lineto commands that do not move the cursor -- `LineTo(0,0)`. 

The [LINESTRING](https://github.com/mapbox/vector-tile-spec/tree/master/2.0#4343-linestring-geometry-type) geometry states only that the command count must be at least one. However, the logic in my decoder is that a `lineto(0,0)` doesn't contribute to the point count and therefore, I throw errors about invalid linestrings in situations where the lineto command count might be 1 or more.

The same is true in [POLYGON](https://github.com/mapbox/vector-tile-spec/tree/master/2.0#4344-polygon-geometry-type) geometries. However, this might be caught by the area requirement for rings. 

The fix might be to clarify this situation in the polygon and linestring types.

**Comment by jfirebaugh** [comment]
So the geometry in question is a LINESTRING consisting of `MoveTo x,y; LineTo 0,0`, and nothing else, and the implementation discards the zero-length LineTo command, and then throws an error because there are no more LineTo commands? I don't think this is in the spirit of the specification. The command count is not zero, it's one. There is no violation of a MUST requirement of the specification.

If you want this geometry to be prohibited by the specification, we should change [4.3.3.2](https://github.com/mapbox/vector-tile-spec/tree/master/2.0#4332-lineto-command) to a MUST NOT in "For any pair of (dX, dY) the dX and dY MUST NOT both be 0."

**Comment by flippmoke** [comment]
I think the intent in 4.3.4.3 and 4.3.4.4 is to have a valid geometries, I do not think a `MoveTo x,y; LineTo 0,0` creates a valid line?

**Comment by artemp** [comment]
@jfirebaugh @flippmoke : I agree re:MUST NOT - "For any pair of (dX, dY) the dX and dY SHOULD NOT both be 0." - reads too vague, implying it can be 0.

**Comment by flippmoke** [comment]
@artemp @jfirebaugh we probably would have to release 2.1 if we changed this wording? Unless I get some buy in to change current spec as we just released it?

**Comment by jfirebaugh** [comment]
We should change 4.3.3.2 to a MUST NOT in "For any pair of (dX, dY) the dX and dY MUST NOT both be 0" for 2.1.
