### ISSUE TITLE
Vector vs Raster tiles size

### ISSUE THREAD

**Issue by jzarzuela** [mapbox/vector-tile-spec#53]
Hi,
I read that vector tiles would be much more space efficient than raster tiles. But comparing what your HTML or iOS demo apps are downloading it doesn't look like so.

For example:

http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/14/4823/6160.vector.pbf?access_token={token}

https://api.mapbox.com/v4/mapbox.streets/14/4823/6160.png?access_token={token}

Results in downloading 16.725 bytes PNG versus 35.206 bytes PBF file.

How is it possible?

**Comment by flippmoke** [comment]
@jzarzuela Great Question!

Let me explain in detail why this file is much more complex, this tile contains a LOT of information and there is a lot you can do with the vector tile! Here is a short list of the number of features in this layer:

![6160](https://cloud.githubusercontent.com/assets/1794907/11919453/e659b216-a718-11e5-8f48-292621cab1cb.png)

This is all to produce this tile: 

![image](https://cloud.githubusercontent.com/assets/1794907/11919460/093118a6-a719-11e5-803c-377e4645bfb8.png)

The important thing to note is that this tile may not just be used to create just one raster tile if you wanted. You can create other raster tiles from zoomed in data! This means it is actually possible to zoom into something much more detailed from this layer with out reloading in GL. 

Here is a debug tool we are working on for vector tiles (that we hope to one day share with everyone), and you can see us zooming in on the data in the tile that you provided for the building layers:

![6160_zoomed](https://cloud.githubusercontent.com/assets/1794907/11919478/b317de0e-a719-11e5-870d-085be1b95006.png)

You can see how much additional detail is provided for just one layer of information! So while:

 16.725 bytes PNG versus 35.206 bytes PBF file. is for the zoom level 14 tile. If that tile is sufficient for all zoom layers between 14 to 18, you have effectively provided information for 4^4 + 1 tiles. So that is roughly (256 * 16.725) bytes worth of PNGs. 

You also contain more information in the vector tile that is not at all used in that style. This means you can:

* Make interactive displays from the data on the client
* Dynamically change styles on the client
* Do spatial analysis on the client
* Inspect the feature attributes in the layer

All of these are not possible with just the raster tile.

**Comment by jzarzuela** [comment]
Thanks for the detailed awnser. It's awesome!.

Just one last question:

Although, as you mention, the same tile could be used for other zoom levels (and safe all the space it claims), as far as I know the framework asks for more tiles using the previous URL as a template in the form of: 
    http://a.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/{zoom}/{x}/{y}.vector.pbf?access_token={token}

So, in fact, it doesn't really safe any space... Does it?

Would it possible to force it to reuse that tile for other zoom level?

Thanks.

**Comment by jfirebaugh** [comment]
The savings comes from two sources:

1. vector tiles for a given zoom level cover 4 times as much area as raster tiles at the same zoom level. So the comparison is more like:

Raster: 16 kb * 4 (67 kb)
PBF: 35 kb (~2x smaller)

2. Vector tile sets have a maximum zoom level (usually z14). Beyond that, the existing tiles are overzoomed (no more tiles are downloaded).

**Comment by mourner** [comment]
Check out this comparison chart I just made: https://plot.ly/~mourner/118.embed

![image](https://cloud.githubusercontent.com/assets/25395/11937050/928f2988-a81a-11e5-9c68-d931b3c08b0c.png)

**Comment by markeberhart** [comment]
Really helpful info! Great way for me to explaining n vector benefits to others.

**Comment by cccruzr** [comment]
@jfirebaugh  Could you please explain a bit this? 

> Vector tile sets have a maximum zoom level (usually z14). Beyond that, the existing tiles are overzoomed (no more tiles are downloaded).

Because having a look on the Browser Developer Tools, it seems that tiles are downloaded for zoom levels larger than 14.

Thanks in advance.

**Comment by flippmoke** [comment]
@cccruzr some resources to understand overzooming:

* https://www.mapbox.com/help/define-overzoom/
* https://github.com/mapbox/vector-tiles/issues/21

**Comment by zxp209** [comment]
How convert the mapbox vector tile to a png tile?
Thanks.

**Comment by springmeyer** [comment]
> How convert the mapbox vector tile to a png tile?

The Mapbox Static API is designed to do that: https://www.mapbox.com/static-maps. Additionally, there are many ways to convert vector tiles into other, visual representations. One of my favorites is vector tile -> svg done by https://github.com/mapbox/mvt-cruncher
