### ISSUE TITLE
Adopt definition of MultiPolygon as defined in OGC SFA (as opposite to OSM)

### ISSUE THREAD

**Issue by sfkeller** [mapbox/vector-tile-spec#78]
The notion of MultiPolygon in the VT 2.1 spec. seems to be inspired by OSM but is not inline with OGC SFA nor with computational geometry. A MultiPolygon in the current VT spec. includes both, a normal polygon with an inner boundary ("hole") and a "real" MultiPolygon. The fact that there's an inner boundary does not make a Polygon a "real" MultiPolygon. OGC SFA says "(...) The boundary of a simple Surface is the set of closed Curves corresponding to its “exterior” and “interior” boundaries (...)" and "A MultiPolygon is a MultiSurface whose elements are Polygons." (see chap. 6.1.10 and 6.1.14 in http://www.opengeospatial.org/standards/sfa ).

In addition, in the "Winding Order" chapter of the VT spec. 2.1 the 4th polygon example with "partially overlapping rings in a multipolygon with different winding orders" (even-odd filling style) is not a valid single polygon according to OGC SFA (see figure 12 in OGC SFA which explicitly tags this geometry as invalid: http://www.opengeospatial.org/standards/sfa ). It's two polygons, possibly forming a "real" MultiPolygon.

**Comment by jfirebaugh** [comment]
I think you may be confused about the difference between Polygons and Multipolygons in the vector tile specification.

A Polygon is an exterior ring, followed by zero or more interior rings. A Multipolygon is two or more Polygons. Whether a ring is "interior" or "exterior" is determined by applying the surveyor's formula, as described in the specification.

#77 covers using an explicit type for Multipolygons, rather than using the surveyor's formula to distinguish interior and exterior rings.

**Comment by sfkeller** [comment]
Thanks for looking at this issue. 
I see now that the VT spec. follows the "correct" Polygon/Multipolygon definition (the difference to OSM still is notable). 
Also, the 4th polygon example in the MB VT guide (https://www.mapbox.com/vector-tiles/specification/ ) still seems unclear to me.
In any case: My main concern is #77 which I strongly support as a VT reader programmer.
