### ISSUE TITLE
Question: Can I use one very large vector tile source, or should I break it into smaller sources?

### ISSUE THREAD

**Issue by sdawson26** [mapbox/vector-tile-spec#85]
In your experience, how big can mbtile files get before they affect performance? Is the rule of thumb to keep each tile <500kb like Mapbox Classic requires?

**Comment by flippmoke** [comment]
This is a set of issues that are specifically about the specification itself -- rather not how to implement the standard. However, I will answer your question to the best of my ability!

Basically vector tiles are general considered to best as small sections of data -- basically only put as much data as you actually need in your tiles. As for MBtiles -- they are simply sql lite databases containing sets of vector tiles so that may grow very large. As for how this will affect performance -- it will greatly depend on how you are extracting data from the MBtiles file. I have no idea how they are indexed and how the internals of SQLite would react to larger/smaller sized buffers (vector tiles).
